entities={
    "helix-tr":{
        "title":"Helix: Holistic Optimization for Accelerating Iterative Machine Learning",
        "link": "http://data-people.cs.illinois.edu/helix-tr.pdf",
        "authors":"Doris Xin, Stephen Macke, Litian Ma, Jialin Liu, Shuchen Song, Aditya Parameswaran",
        "type": "45th International Conference on Very Large Data Bases (VLDB)",
        "location": "Los Angeles, USA", 
        "date": "September 2019",
    },
    "dataspread-formula":{
        "title":"Anti-Freeze for Large and Complex Spreadsheets: Asynchronous Formula Computation",
        "link": "nowhere.html",
        "authors":"Mangesh Bendre, Tana Wattanawaroon, Kelly Mack, Kevin Chang, Aditya Parameswaran",
         "type":"SIGMOD Int'l Conf. on Management of Data", 
        "location": "Amsterdam, The Netherlands", 
        "date": "June 2019",
    },
    "causality":{
        "title": "An Exploratory User Study of Visual Causality Analysis",
        "link": "nowhere.html",
        "authors":"Chi-Hsien Yen, Aditya Parameswaran, Wai-Tat Fu",
        "type": "21st Eurographics Conference on Visualization (EuroVis)",
        "location": "Porto, Portugal",
        "date": "June 2019",
    },
    "dataspread-nav":{
        "title":"Extending Spreadsheets to Support Seamless Navigation at Scale",
        "link": "nowhere.html",
        "authors": "Sajjadur Rahman, Mangesh Bendre, Pingjing Yang, Yuyang Liu, Shichu Zhu, Zhaoyuan Su, Kevin Chang, Karrie Karahalios, Aditya Parameswaran",
        "type": "Technical Report",
        "date": "April 2019",
    },
    "dataspread-demo2":{
        "title":"Faster, Higher, Stronger: Redesigning Spreadsheets for Scale (Demo)",
        "link":"http://data-people.cs.illinois.edu/papers/dataspread-demo2.pdf",
        "authors":"Mangesh Bendre, Tana Wattanawaroon, Sajjadur Rahman, Kelly Mack, Yuyang Liu, Shichu Zhu, Yu Lu, Ping-Jing Yang, Xinyan Zhou, Kevin Chang, Karrie Karahalios, Aditya Parameswaran",
        "type": "35th International Conf. on Data Engineering (ICDE)",
        "location": "Macau", 
        "date": "April 2019",
    },
    "vispilot":{
        "title":"Avoiding drill-down fallacies with VisPilot: assisted exploration of data subsets",
        "link": "http://data-people.cs.illinois.edu/papers/vispilot.pdf",
        "authors":"Doris Jung-Lin Lee, Himel Dev, Huizi Hu, Hazem Elmeleegy, Aditya Parameswaran",
        "type": "24th International Conference on Intelligent User Interfaces (IUI)",
        "location": "Los Angeles, USA", 
        "date": "March 2019",
    },
    "sorting":{
        "title": "Holistic Crowd-Powered Sorting via AID: Optimizing for Accuracies, Inconsistencies, and Difficulties",
        "link": "nowhere.html",
        "authors":"Shreya Rajpal and Aditya Parameswaran",
        "type": "27th International Conference on Information and Knowledge Management (CIKM)",
        "location": "Lingotto, Italy",
        "date": "October 2018"
    },
    "vida":{
        "title": "The Case for a Visual Discovery Assistant: A Holistic Solution for Accelerating Visual Data Exploration",
        "link": "http://data-people.cs.illinois.edu/vida.pdf",
        "authors":"Doris Jung-Lin Lee and Aditya Parameswaran",
        "type": "IEEE Data Engineering Bulletin",
        "location": "Issue on Insights and Explanations in Data Analysis",
        "date": "September 2018"  
    },
    "dataspread-mental-models":{
        "title":"“It’s a grid, it’s a form, it’s a spreadsheet!”: Revisiting Sensemaking with Spreadsheets for Presentation and Data Analysis",
        "authors":"Pingjing Yang, Sajjadur Rahman, Mangesh Bendre, Joon Sung Park, Kevin Chang, Karrie Karahalios, Aditya Parameswaran",
        "type": "Technical Report",
        "date": "September 2018"
    },
    "fastmatch": {
        "title": "Adaptive Sampling for Rapidly Matching Histograms",
        "link": "https://arxiv.org/abs/1708.05918",
        "authors": "Stephen Macke, Yiming Zhang, Silu Huang, Aditya Parameswaran",
        "type": "44th International Conference on Very Large Data Bases (VLDB)",
        "location": "Rio de Janeiro, Brazil", 
        "date": "September 2018",
    },
    "shapesearch-demo":{
        "title":"ShapeSearch: Flexible Pattern-based Querying of Trend Line Visualizations (Demo)",
        "link": "http://www.vldb.org/pvldb/vol11/p1962-siddiqui.pdf",
        "authors":"Tarique Siddiqui, Paul Luh, Zesheng Wang, Karrie Karahalios, Aditya Parameswaran",
        "type": "44th International Conference on Very Large Data Bases (VLDB)",
        "location": "Rio de Janeiro, Brazil", 
        "date": "September 2018",
    },
    "helix-demo":{
        "title":"Helix: Accelerating Human-in-the-loop Machine Learning (Demo)",
        "link": "http://data-people.cs.illinois.edu/papers/p871-xin.pdf",
        "authors":"Doris Xin, Litian Ma, Jialin Liu, Stephen Macke, Shuchen Song, Aditya Parameswaran",
        "type": "44th International Conference on Very Large Data Bases (VLDB)",
        "location": "Rio de Janeiro, Brazil", 
        "date": "September 2018",
    },
    "helix-survey":{
        "title": "How Developers Iterate on Machine Learning Workflows -- A Survey of the Applied Machine Learning Literature",
        "link": "https://arxiv.org/abs/1803.10311",
        "authors": "Doris Xin, Litian Ma, Shuchen Song, Aditya Parameswaran",
        "type": "IDEA Workshop at KDD Int'l Conf. on Knowledge Discovery and Data Mining",
        "location": "London, UK",
        "date": "August 2018",
    },
    "dataspread-vision":{
        "title":"Directed Data Management: A New Frontier in Database Usability",
        "link":"http://dataspread.github.io/papers/vision.pdf",
        "authors":"Mangesh Bendre, Sajjadur Rahman, Tana Wattanawaroon, Kelly Mack, Yu Lu, Kevin Chang, Karrie Karahalios, Aditya Parameswaran",
        "type": "Technical Report",
        "date": "August 2018"
    },
    "segmentation":{
        "title": "Quality Evaluation Methods for Crowdsourced Image Segmentation",
        "link": "http://ilpubs.stanford.edu:8090/1161/1/main.pdf",
        "authors": "Doris Jung-Lin Lee, Akash Das Sarma, Aditya Parameswaran",
        "type": "6th International Conference on Human Computation and Crowdsourcing (HCOMP)",
        "location": "Zurich, Switzerland",
        "date": "July 2018",
    },
     "datamaran": {
        "title": "Navigating the Data Lake with Datamaran: Automatically Extracting Structure from Log Datasets",
        "link": "https://arxiv.org/abs/1708.08905",
        "authors": "Yihan Gao, Silu Huang, Aditya Parameswaran",
        "type":"SIGMOD Int'l Conf. on Management of Data", 
        "location": "Houston, USA", 
        "date": "June 2018",
    },
    "needletail":{
        "title": "Optimally Leveraging Density and Locality to Support LIMIT Queries",
        "link": "https://arxiv.org/abs/1611.04705",
        "authors": "Albert Kim, Liqi Xu, Tarique Siddiqui, Silu Huang, Sam Madden, Aditya Parameswaran",
        "type": "HILDA Workshop at SIGMOD Int'l Conf. on Management of Data",
        "location": "Houston, USA", 
        "date": "June 2018",
    },
    "helix-vision": {
        "title":"Accelerating Human-in-the-loop Machine Learning: Challenges and Opportunities",
        "link": "https://arxiv.org/pdf/1804.05892.pdf",
        "authors":"Doris Xin, Litian Ma, Jialin Liu, Stephen Macke, Shuchen Song, Aditya Parameswaran",
        "type": "DEEM Workshop at SIGMOD Int'l Conf. on Management of Data",
        "location": "Houston, USA", 
        "date": "June 2018",
    },
     "data-diff-demo": {
        "title": "DataDiff: User-Interpretable Data Transformation Summaries for Collaborative Data Analysis (Demo)",
        "link": "nowhere.html",
        "authors": "Gunce Yilmaz,  Tana Wattanawaroon,  Liqi Xu, Abhishek Nigam,  Aaron Elmore,  Aditya Parameswaran",        
        "type":"SIGMOD Int'l Conf. on Management of Data", 
        "location": "Houston, USA", 
        "date": "June 2018",
     },
     "dataspread": {
        "title": "Towards a Holistic Integration of Spreadsheets with Databases: A Scalable Storage Engine for Presentational Data Management",
        "link": "https://arxiv.org/abs/1708.06712",
        "authors": "Mangesh Bendre, Vipul Venkataraman, Xinyan Zhou, Kevin Chang, Aditya Parameswaran",
        "type": "34th International Conf. on Data Engineering (ICDE)",
        "location": "Paris, France",
        "date": "April 2018"
    },
    "dataspread-reddit": {
        "title": "Characterizing Scalability Issues in Spreadsheet Software using Online Forums (Case Study Paper)",
        "link": "http://data-people.cs.illinois.edu/papers/dataspread-reddit.pdf",
        "authors": "Kelly Mack, John Lee, Kevin Chang, Karrie Karahalios, Aditya Parameswaran",
        "type": "International Conference on Human Factors in Computing Systems (CHI)",
        "location": "Montreal, Canada",
        "date": "April 2018"
    },
    "uniform-conv": {
        "title": "On the Interpretability of Conditional Probability Estimates in the Agnostic Setting",
        "link": "http://arxiv.org/abs/1506.03018",
        "authors": "Yihan Gao, Aditya Parameswaran, Jian Peng",
        "type": "Electronic Journal of Statistics, Volume 11, Number 2",
        "location": "(Special Issue of AISTATS 2017 Best Papers)",
        "date": "January 2018",
    },
    "datadiff": {
        "title": "Towards a Theory of Data-Diff: Optimal Synthesis of Succinct Data Modification Scripts",
        "link": "papers/datadiff.pdf",
        "authors": "Tana Wattanawaroon, Stephen Macke, Aditya Parameswaran",
        "type": "Technical Report",
        "date": "December 2017"
    },
    "zenvisage-chi": {
        "title": "You can't always sketch what you want: Understanding Sensemaking in Visual Query Systems",
        "link": "https://arxiv.org/pdf/1710.00763.pdf",
        "authors": "Doris Jung-Lin Lee, John Lee, Tarique Siddiqui, Jaewoo Kim, Karrie Karahalios, Aditya Parameswaran",
        "type": "Technical Report",
        "date": "October 2017"
    },
    "vizinc": {
        "title": "I've Seen Enough: Incrementally Improving Visualizations to Support Rapid Decision Making",
        "link": "http://data-people.cs.illinois.edu/papers/incvisage-paper.pdf",
        "authors": "Sajjadur Rahman, Maryam Aliakbarpour, Ha Kyung Kong, Eric Blais, Karrie Karahalios, Aditya Parameswaran, Ronitt Rubinfeld",
        "type": "43rd International Conference on Very Large Data Bases (VLDB)",
        "location": "Munich, Germany",
        "date": "September 2017"
    },
    "orpheus":{
        "title": "OrpheusDB: Bolt-on Versioning for Relational Databases",
        "link": "https://arxiv.org/abs/1703.02475",
        "authors": "Silu Huang, Liqi Xu, Jialin Liu, Aaron Elmore, Aditya Parameswaran",
        "type": "43rd International Conference on Very Large Data Bases (VLDB)",
        "location": "Munich, Germany",
        "date": "September 2017",
        "special":"(Invited to: Special Issue of VLDB Journal for VLDB 2017 Best Papers)"
    },
    "zenvisage":{
        "title": "Effortless Visual Data Exploration with Zenvisage: An Interactive and Expressive Visual Analytics System",
        "link": "http://data-people.cs.illinois.edu/papers/zenvisage-vldb.pdf",
        "authors": "Tarique Siddiqui, Albert Kim, John Lee, Karrie Karahalios, Aditya Parameswaran",
        "type": "43rd International Conference on Very Large Data Bases (VLDB)",
        "location": "Munich, Germany",
        "date": "September 2017"
        },
    "crowd-data":{
        "title": "Understanding Workers, Developing Effective Tasks, and Enhancing Marketplace Dynamics: A Study of a Large Crowdsourcing Marketplace",
        "link": "http://data-people.cs.illinois.edu/papers/crowd-data.pdf",
        "authors": "Ayush Jain, Akash Das Sarma, Jennifer Widom, Aditya Parameswaran",
        "type": "43rd International Conference on Very Large Data Bases (VLDB)",
        "location": "Munich, Germany",
        "date": "September 2017"
        },
  
    "orpheus-demo":{
        "title": "OrpheusDB: A Light-weight Approach to Relational Dataset Versioning (Demo)",
        "link": "http://data-people.cs.illinois.edu/papers/orpheus-demo.pdf",
        "authors": "Liqi Xu, Silu Huang, Sili Hui, Aaron Elmore, Aditya Parameswaran",
        "type": "SIGMOD Int'l Conf. on Management of Data", 
        "location": "Chicago, USA", 
        "date": "June 2017",
        "special":"(Best Demo Honorable Mention)"
  
    },
    "slimfast":{
        "title": "SLiMFast: Guaranteed Results for Data Fusion and Source Reliability",
        "link": "https://arxiv.org/abs/1512.06474",
        "authors": "Theo Rekatsinas, Manas Joglekar, Hector Garcia-Molina, Aditya Parameswaran, and Chris Re",
        "type": "SIGMOD Int'l Conf. on Management of Data", 
        "location": "Chicago, USA", 
        "date": "June 2017"
    },
    "uniform-conv-conf":{
        "title": "On the Interpretability of Conditional Probability Estimates in the Agnostic Setting (ORAL Presentation)",
        "link": "http://arxiv.org/abs/1506.03018",
        "authors": "Yihan Gao, Aditya Parameswaran, Jian Peng",
        "type": "20th Intl. Conf. on Artificial Intelligence and Statistics (AISTATS)",
        "location": "Ft. Lauderdale, USA",
        "date": "April 2017",
        "special":"(Invited to: Special Issue of the Electronic Journal of Statistics)"
    },
    "smart-drill-down-tkde":{
        "title": "Interactive Data Exploration with Smart Drill-Down",
        "link": "http://arxiv.org/abs/1412.0364",
        "authors" : "Manas Joglekar, Hector Garcia-Molina, Aditya Parameswaran",
        "type" : "TKDE Journal",
        "location": "(Special Issue of ICDE 2016 Best Papers)",
        "date" : "March 2017",
    },
    "zenvisage-cidr":{
        "title": "Fast-forwarding to Desired Visualizations with Zenvisage",
        "link": "http://data-people.cs.illinois.edu/papers/zenvisage-cidr.pdf",
        "authors": "Tarique Siddiqui, John Lee, Albert Kim, Edward Xue, Xiaofo Yu, Sean Zou, Lijin Guo, Changfeng Liu, Chaoran Wang, Karrie Karahalios, Aditya Parameswaran",
        "type": "Conference on Innovative Database Research (CIDR)", 
        "location": "Chaminade, USA",
        "date":  "January 2017"
        },
    "open-ended":{
        "title": "Optimizing Open-Ended Crowdsourcing: The Next Frontier in Crowdsourced Data Management",
        "link": "https://arxiv.org/abs/1610.05377",
        "authors": "Aditya Parameswaran, Akash Das Sarma, Vipul Venkataraman",
        "type": "IEEE Data Engineering Bulletin",
        "location": "Issue on Human-in-the-loop Data Management",
        "date": "December 2016"        
    },
    "vizrec-sigmod":{
        "title": "Towards Visualization Recommendation Systems",
        "link": "https://t.co/gE3N36Igg7",
        "authors": "Manasi Vartak, Silu Huang, Tarique Siddiqui, Samuel Madden, and Aditya Parameswaran",
        "type": "SIGMOD Record",
        "location": "Chicago, USA",
        "date": "December 2016"
    },
    "orchestra":{
        "title": "It's a Matter of Perspective(s): Crowd-Powered Consensus Organization of Corpora",
        "link": "https://arxiv.org/abs/1601.02034",
        "authors": "Ayush Jain, Karan Goel, Joon Young Seo, Andrew Kuznetsov, Aditya Parameswaran, Hari Sundaram",        
        "type": "Technical Report",
        "date": "November 2016"
    },
    "facet-gist":{
        "title": "FacetGist: Collective Extraction of Document Facets in Large Technical Corpora",
        "link": "nowhere.html",
        "authors":"Tarique Siddiqui, Xiang Ren, Aditya Parameswaran, and Jiawei Han",
        "type": "25th International Conference on Information and Knowledge Management (CIKM)",
        "location": "Indianapolis, USA",
        "date": "October 2016"
    },
    "seedb-paper":{
       "title": "SeeDB: Efficient Data-Driven Visualization Recommendations to Support Visual Analytics",  
        "link": "http://data-people.cs.illinois.edu/seedb-tr.pdf", 
        "authors": "Manasi Vartak, Sajjadur Rahman, Samuel Madden, Aditya Parameswaran, and Neoklis Polyzotis",
        "type": "42nd International Conference on Very Large Data Bases (VLDB)", 
        "location": "New Delhi, India",
       "date": "September 2016"
    },
    "decibel":{
        "title": "Decibel: The Relational Dataset Branching System",
        "link": "http://data-people.cs.illinois.edu/decibel-tr.pdf", 
        "authors": "Michael Maddox, David Goehring, Aaron Elmore, Sam Madden, Aditya Parameswaran, and Amol Deshpande",
        "type": "42nd International Conference on Very Large Data Bases (VLDB)", 
        "location": "New Delhi, India",
        "date": "September 2016"
    },
    "squish": {
        "title": "Squish: Near-optimal Compression for Archival of Relational Datasets",  
        "link": "http://arxiv.org/abs/1602.04256", 
        "authors": "Yihan Gao, and Aditya Parameswaran",
        "type": "22nd International Conf. on Knowledge Discovery and Data Mining (KDD)", 
        "location": "San Francisco, USA",
        "date": "August 2016"
    },
    "global": {
        "title": "Towards Globally Optimal Crowdsourcing Quality Management",
        "link": "http://data-people.cs.illinois.edu/papers/param-est.pdf",
        "authors" : "Akash Das Sarma, Aditya Parameswaran, Jennifer Widom",
        "type": "SIGMOD International Conf. on Management of Data", 
        "location": "San Francisco, USA",
        "date" : "June 2016"
    },
    "smart-drill-down": {
        "title": "Interactive Data Exploration with Smart Drill-Down",
        "link": "http://arxiv.org/abs/1412.0364",
        "authors" : "Manas Joglekar, Hector Garcia-Molina, Aditya Parameswaran",
        "type" : "32nd International Conf. on Data Engineering (ICDE)",
        "location": "Helsinki, Finland",
        "date" : "May 2016",
        "special":"(Invited to: Special Issue of TKDE Journal for ICDE 2016 Best Papers)"
        },
    "challenges-crowd":{
        "title": "Challenges in Data Crowdsourcing",
        "link": "http://data-people.cs.illinois.edu/nowhere.html",
        "authors": "Hector Garcia-Molina, Manas Joglekar, Adam Marcus, Aditya Parameswaran, and Vasilis Verios",
        "type": "IEEE TKDE: Transactions on Knowledge and Data Engineering",
        "location": "(Pages XX-YY)",
        "date": "January 2016"
    },
    "crowd-book": {
        "title": "Crowdsourced Data Management: Industry and Academic Perspectives (Book)",
        "link": "http://data-people.cs.illinois.edu/papers/crowd-book.pdf",
        "authors": "Adam Marcus and Aditya Parameswaran",
        "type": "Foundations and Trends® in Databases",
        "location": "Vol. 6: No. 1-2, pp 1-161",
        "date": "December 2015"
    },
    "jellybean":{
       "title": "Surpassing Humans and Computers with JellyBean: Crowd-Vision-Hybrid Image Counting Algorithms",  
        "link": "http://ilpubs.stanford.edu:8090/1128/", 
        "authors": "Akash Das Sarma, Ayush Jain, Arnab Nandi, Aditya Parameswaran and Jennifer Widom",
        "type": "3rd International Conference on Human Computation and Crowdsourcing (HCOMP)",
        "location": "San Diego, USA",
        "date": "November 2015"
    },
    "vizrec":{
        "title": "Towards Visualization Recommendation Systems",
        "link": "http://data-people.cs.illinois.edu/papers/dsia.pdf",
        "authors": "Manasi Vartak, Silu Huang, Tarique Siddiqui, Samuel Madden, and Aditya Parameswaran",
        "type": "1st Workshop on Data Systems for Interactive Analytics (DSIA)",
        "location": "Chicago, USA",
        "date": "October 2015"
    },
    "version-theory":{
       "title": "Principles of Dataset Versioning: Exploring the Recreation/Storage Tradeoff",  
        "link": "http://arxiv.org/abs/1505.05211", 
        "authors": "Souvik Bhattacherjee, Amit Chavan, Silu Huang, Amol Deshpande, and Aditya Parameswaran",
         "type": "41st International Conference on Very Large Data Bases (VLDB)", 
        "location": "Kohala Coast, Hawaii, USA",
        "date": "September 2015"
    },
    "pricing": {
        "title": "Finish Them!: Pricing Algorithms for Human Computation",  
        "link": "http://arxiv.org/abs/1408.6292", 
        "authors": "Yihan Gao, Aditya Parameswaran",
        "type": "41st International Conference on Very Large Data Bases (VLDB)", 
        "location": "Kohala Coast, Hawaii, USA",
       "date": "September 2015"},
    "intel-sample":{
        "title": "Rapid Sampling for Visualizations with Ordering Guarantees",
        "link": "http://arxiv.org/abs/1412.3040",
        "authors": "Albert Kim, Eric Blais, Aditya Parameswaran, Piotr Indyk, Samuel Maddem, Ronitt Rubinfeld",
        "type": "41st International Conference on Very Large Data Bases (VLDB)", 
        "location": "Kohala Coast, Hawaii, USA",
        "date": "September 2015"
    },
    "data-spread-demo": {
        "title": "Data-Spread: Unifying Databases and Spreadsheets (Demo)",
        "link": "http://data-people.cs.illinois.edu/papers/data-spread-demo.pdf",
        "authors": "Mangesh Bendre, Bofan Sun, Xinyan Zhou, Ding Zhang, Shy-Yauer Lin, Kevin Chang, and Aditya Parameswaran",
         "type": "41st International Conference on Very Large Data Bases (VLDB)", 
        "location": "Kohala Coast, Hawaii, USA",
       "date": "September 2015"},  
    "smart-drill-down-demo": {
        "title": "Smart Drill-down: A New Data Exploration Operator (Demo)",
        "link": "http://data-people.cs.illinois.edu/papers/TableSummarizationDemo.pdf",
        "authors" : "Manas Joglekar, Hector Garcia-Molina, Aditya Parameswaran",
         "type": "41st International Conference on Very Large Data Bases (VLDB)", 
        "location": "Kohala Coast, Hawaii, USA",
       "date": "September 2015"},
    "datahub-demo": {
        "title":"Collaborative Data Analytics with Datahub (Demo)",
        "link": "http://data-people.cs.illinois.edu/papers/datahubdemo.pdf",
        "authors": "Anant Bhardwaj, Amol Deshpande, Aaron Elmore, David Karger, Sam Madden, Aditya Parameswaran, Harihar Subramanyam, Eugene Wu, and Rebecca Zhang",
         "type": "41st International Conference on Very Large Data Bases (VLDB)", 
        "location": "Kohala Coast, Hawaii, USA",
       "date": "September 2015"},
    "batch-crowds":{
       "title": "Debiasing Crowdsourced Batches",  
        "link": "http://data-people.cs.illinois.edu/papers/betamain.pdf", 
        "authors": "Honglei Zhuang, Aditya Parameswaran, Dan Roth, and Jiawei Han",
        "type": "21th International Conf. on Knowledge Discovery and Data Mining (KDD)", 
        "location": "Sydney, Australia",
        "date": "August 2015"
     },
    "version-ql":{
        "title": "Towards a Unified Query Language for Provenance and Versioning",
        "link": "http://data-people.cs.illinois.edu/papers/datahubtapp.pdf",
        "authors": "Amit Chavan, Silu Huang, Amol Deshpande, Aaron Elmore, Sam Madden, and Aditya Parameswaran",
        "type": "7th International Workshop on Theory and Practice of Provenance (TaPP)",
        "location": "Edinburgh, Scotland",
        "date":"July 2015"
    },
    "correlations":{
        "title": "Exploiting Correlations for Evaluating Complex Queries",  
        "link": "http://arxiv.org/abs/1411.3374", 
        "authors": "Manas Joglekar, Hector Garcia-Molina,  Aditya Parameswaran and Christopher Re",
        "type": "SIGMOD International Conf. on Management of Data", 
        "location": "Melbourne, Australia",
        "date": "May 2015"
    },
     "confidence-general": {
        "title": "Comprehensive and Reliable Crowd Assessment Algorithms",  
        "link": "http://arxiv.org/abs/1411.3377", 
        "authors": "Manas Joglekar, Hector Garcia-Molina, and Aditya Parameswaran ",
        "type": "31st International Conf. on Data Engineering (ICDE)", 
        "location": "Seoul, Korea",
        "date": "April 2015",
    },
    "datahub":{
       "title": "DataHub: Collaborative Data Science & Dataset Version Management at Scale",
       "link": "http://arxiv.org/abs/1409.0798",
       "authors": "Anant Bhardwaj, Souvik Bhattacherjee, Amit Chavan, Amol Deshpande, Aaron J. Elmore, Samuel Madden, Aditya Parameswaran",
       "type": "Conference on Innovative Database Research (CIDR)", 
        "location": "Asilomar, USA",
        "date":  "January 2015"
    },
    "geohash":{
      "title": "GeoHashViz: Interactive Analytics for Mapping Spatiotemporal Diffusion of Twitter Hashtags",
      "link": "nowhere.html",
      "authors": "Kiumars Soltani, Shaowen Wang, and Aditya Parameswaran",
      "type": "XSEDE",
      "location": "Miami, USA",
      "date": "2015"
    },
    "crowdgather": {
        "title": "CrowdGather: Entity Extraction over Structured Domains",
        "link": "http://data-people.cs.illinois.edu/papers/crowd-gather.pdf",
        "authors" : "Theodoros Rekatsinas, Amol Deshpande, Aditya Parameswaran",
        "type" : "Technical Report",
        "date" : "November 2014"},
    
    "accuracy-lattice":{
	   "title": "Optimal Worker Quality and Answer Estimates in Crowd-Powered Filtering and Rating",
	   "link": "http://ilpubs.stanford.edu:8090/1098/",
	   "authors":"Akash Das Sarma, Aditya Parameswaran, Jennifer Widom",
	   "type": "2nd International Conference on Human Computation and Crowdsourcing (HCOMP)",
	   "location": "Pittsburgh, USA",
	   "date": "November 2014"
	},
    
    "seedb-demo":{
        "title": "SeeDB: Automatically Generating Query Visualizations (Demo)",  
        "link": "http://www.vldb.org/pvldb/vol7/p1581-vartak.pdf", 
        "authors": "Manasi Vartak, Samuel Madden, Aditya Parameswaran, Neoklis Polyzotis",
        "type": "40th International Conf. on Very Large Data Bases (VLDB)", 
        "location": "Hangzhou, China",
        "date": "September 2014"},
    "generalizations":{
        "title": "Optimal Crowd-Powered Rating and Filtering Algorithms", 
        "link": "http://ilpubs.stanford.edu:8090/1078/", 
        "authors": "Aditya Parameswaran, Stephen Boyd, Hector Garcia-Molina, Ashish Gupta, Neoklis Polyzotis, Jennifer Widom", 
        "type": "40th International Conf. on Very Large Data Bases (VLDB)", 
        "location": "Hangzhou, China",
        "date": "September 2014"
        },
    "seedb":{
        "title": "SeeDB: Visualizing Database Queries Efficiently (Vision Paper)",  
        "link": "http://ilpubs.stanford.edu:8090/1076/",  
        "authors": "Aditya Parameswaran, Neoklis Polyzotis, and Hector Garcia-Molina", 
        "type": "40th International Conf. on Very Large Data Bases (VLDB)", 
        "location": "Hangzhou, China",
        "date": "September 2014"}, 
    "csp":{
	   "title": "Indexing Cost-Sensitive Prediction",
	   "link": "http://arxiv.org/abs/1408.4072",
	   "authors" : "Leilani Battle, Edward Benson, Aditya Parameswaran, Eugene Wu",
	   "type" : "Technical Report",
	   "date" : "August 2014"},
    "datasift-demo":{
        "title": "DataSift: A Crowd-Powered Search Toolkit (Demo)",  
        "link": "http://ilpubs.stanford.edu:8090/1091/", 
        "authors": "Aditya Parameswaran, Ming Han Teh, Hector Garcia-Molina and Jennifer Widom", 
        "type": "SIGMOD International Conf. on Management of Data", 
        "location": "Snowbird, Utah, USA",
        "date": "June 2014"},
    "needletail-demo":{
        "title": "NeedleTail: A System for Browsing Queries (Demo)",  
        "link": "http://data-people.cs.illinois.edu/papers/needletail-demo.pdf", 
        "authors": "Albert Kim, Samuel Madden and Aditya Parameswaran ",
        "type": "Technical Report",
        "date": "April 2014"},
    "find": {
        "title": "Crowd-Powered Find Algorithms",  
        "link": "http://ilpubs.stanford.edu:8090/1049/", 
        "authors": "Anish Das Sarma, Aditya Parameswaran, Hector Garcia-Molina and Alon Halevy", 
        "type": "30th International Conf. on Data Engineering (ICDE)", 
        "location": "Chicago, USA",
        "date": "April 2014",
        "special":"(Invited to: Special Issue of TKDE Journal for ICDE 2014 Best Papers)"},
    "parsing": {
        "title": "Efficient Parsing-based Keyword Search over Databases",  
        "link": "http://ilpubs.stanford.edu:8090/1057/",  
        "authors": "Aditya Parameswaran, Raghav Kaushik and Arvind Arasu", 
        "type": "22th International Conf. on Information and Knowledge Management (CIKM)", 
        "location": "Burlingame, USA",
        "date": "November 2013"},
    "datasift": {
        "title": "An Expressive and Accurate Crowd-Powered Search Toolkit",  
        "link": "http://ilpubs.stanford.edu:8090/1068/", 
        "authors": "Aditya Parameswaran, Ming Han Teh, Hector Garcia-Molina and Jennifer Widom", 
        "type": "1st Conf. on Human Computation and Crowdsourcing (HCOMP)",
        "location": "Palm Springs, USA", 
        "date": "November 2013"},
    "thesis": {
        "title": "Human-Powered Data Management",  
        "link": "http://data-people.cs.illinois.edu/aditya-thesis.pdf",  "authors": "Aditya Parameswaran", 
        "type": "Doctoral Dissertation", 
        "location": "Stanford University", 
        "date": "September 2013",
        "special": "(Thesis awards: Stanford U., SIGMOD's Jim Gray award, and SIGKDD's thesis award Runner-up)",},
    "sampling-guarantees": {
        "title": "Active Sampling for Entity Matching with Guarantees",  
        "link": "http://ilpubs.stanford.edu:8090/1056/",   
        "authors": "Kedar Bellare, Suresh Iyengar, Aditya Parameswaran and Vibhor Rastogi",
        "type": "ACM Transactions on Knowledge Discovery from Data (TKDD) - Special Issue on ACM SIGKDD 2012",
        "location": "Volume 7(3)", 
        "date": "September 2013",
    },
    "confidence": {
        "title": "Evaluating the Crowd with Confidence",  
        "link": "http://ilpubs.stanford.edu:8090/1051/", 
        "authors": "Manas Joglekar, Hector Garcia-Molina and Aditya Parameswaran", 
        "type": "19th International Conf. on Knowledge Discovery and Data Mining (KDD)", 
        "location": "Chicago, USA", 
        "date": "August 2013"},
    "deco-survey": { 
        "title": "An Overview of the Deco System: Data Model and Query Language; Query Processing and Optimization",  
        "link": "http://ilpubs.stanford.edu:8090/1059/", 
        "authors": "Hyunjung Park, Richard Pang, Aditya Parameswaran, Hector Garcia-Molina, Neoklis Polyzotis, and Jennifer Widom", 
        "type": "SIGMOD Record", 
        "location": "Volume 41", 
        "date": "December 2012"},
    "pipelines": {
        "title": "Human-Powered Debugging of Large Data Pipelines",  
        "link": "http://ilpubs.stanford.edu:8090/1019/", 
        "authors": "Nilesh Dalvi, Aditya Parameswaran and Vibhor Rastogi", 
        "type": "25th International Conf. on Neural Information Processing Systems (NIPS)", 
        "location": "Tahoe, Nevada, USA",
        "date":  "December 2012"},
    "deco": {
        "title": "Deco: Declarative Crowdsourcing",  
        "link": "http://ilpubs.stanford.edu:8090/1015/", 
        "authors": "Aditya Parameswaran, Hyunjung Park, Hector Garcia-Molina, Neoklis Polyzotis and Jennifer Widom", 
        "type": "21th International Conf. on Information and Knowledge Management (CIKM)", 
        "location": "Maui, Hawaii, USA",
        "date":  "November 2012",
    },
    "deco-demo":{
        "title": "Deco: A System for Declarative Crowdsourcing (Demo)",  
        "link": "http://ilpubs.stanford.edu:8090/1034/", 
        "authors": "Hyunjung Park, Richard Pang, Aditya Parameswaran, Hector Garcia-Molina, Neoklis Polyzotis and Jennifer Widom", 
        "type": "38th International Conf. on Very Large Data Bases (VLDB)", 
        "location": "Istanbul, Turkey",
        "date":  "September 2012",
    },
    "deco-qp":{
        "title": "Query Processing over Crowdsourced Data",  
        "link": "http://ilpubs.stanford.edu:8090/1052/", 
        "authors": "Hyunjung Park, Aditya Parameswaran and Jennifer Widom",
        "type": "Infolab Technical Report",
        "date":  "August 2012",
    },
    "sampling":{
        "title": "Active Sampling for Entity Matching",  
        "link": "http://ilpubs.stanford.edu:8090/1036/",  
        "talklink": "talks/KDD2012.pptx",
        "authors": "Kedar Bellare, Suresh Iyengar, Aditya Parameswaran and Vibhor Rastogi", 
        "type": "18th International Conf. on Knowledge Discovery and Data Mining (KDD)", "location": "Beijing, China",
        "date":  "August 2012",
        "special":"(Invited to: Special Issue of TKDD Journal for KDD 2012 Best Papers)",
    },
    "swiftly":{
        "title": "Identifying Reliable Workers Swiftly",  
        "link": "http://ilpubs.stanford.edu:8090/1043", 
        "authors": "Aditya Ramesh, Aditya Parameswaran, Hector Garcia-Molina and Neoklis Polyzotis", 
        "type": "Infolab Technical Report",
        "date":  "June 2012"},
    "max":{
        "title": "So Who Won? Dynamic Max Discovery with the Crowd",  
        "link": "http://ilpubs.stanford.edu:8090/1032/", 
        "authors": "Stephen Guo, Aditya Parameswaran and Hector Garcia-Molina", 
        "type": "SIGMOD International Conf. on Management of Data", 
        "location": "Scottsdale, Arizona, USA",
        "date":  "June 2012"},
    "crowdscreen":{
        "title": "CrowdScreen: Algorithms for Filtering Data with Humans",  
        "link": "http://ilpubs.stanford.edu:8090/1011",  
        "talklink": "talks/CrowdScreenTalk.pptx",
        "authors": "Aditya Parameswaran, Hector Garcia-Molina, Hyunjung Park, Neoklis Polyzotis, Aditya Ramesh and Jennifer Widom", 
        "type": "SIGMOD International Conf. on Management of Data", 
        "location": "Scottsdale, Arizona, USA",
        "date":  "June 2012"},
    "fuzzy-joins":{
        "title": "Fuzzy Joins using MapReduce",  
        "link": "http://ilpubs.stanford.edu:8090/1006", 
        "authors": "Foto Afrati, Anish Das Sarma, David Menestrina, Aditya Parameswaran and Jeffrey D. Ullman", 
        "type": "28th International Conf. on Data Engineering (ICDE)", 
        "location": "Washington DC, USA",
        "date":  "April 2012",
        },
    "cacm":{
        "title": "Information Seeking: Convergence of Search, Recommendations and Advertising",  
        "link": "http://ilpubs.stanford.edu:8090/963", 
        "authors": "Hector Garcia-Molina, Georgia Koutrika and Aditya Parameswaran", 
        "type": "Communications of the ACM", 
        "location": "Viewpoint Article",
        "date":  "November 2011",
        },
    "complex-constraints":{
        "title": "Recommendation Systems with Complex Constraints: A CourseRank Perspective",  
        "link": "http://ilpubs.stanford.edu:8090/909", 
        "authors": "Aditya Parameswaran, Petros Venetis and Hector Garcia-Molina", 
        "type": "ACM Transactions on Information Systems", 
        "location": "Volume 29(4)",
        "date":  "November 2011"},
    "robust-wrappers":{
        "title": "Optimal Schemes for Robust Web Extraction",  
        "link": "http://ilpubs.stanford.edu:8090/998",  
        "talklink": "talks/parameswaran-robust.pptx",
        "authors": "Aditya Parameswaran, Nilesh Dalvi, Hector Garcia-Molina and Rajeev Rastogi",
        "type": "37th International Conf. on Very Large Data Bases (VLDB)", 
        "location": "Seattle, USA",
        "date":  "September 2011",
        },
    "humangs":{
        "title": "Human-assisted Graph Search: It's Okay to Ask Questions",  
        "link": "http://ilpubs.stanford.edu:8090/970",  
        "talklink": "talks/parameswaran-humangs.pptx",
        "authors": "Aditya Parameswaran, Anish Das Sarma, Hector Garcia-Molina, Neoklis Polyzotis and Jennifer Widom",
        "type": "37th International Conf. on Very Large Data Bases (VLDB)", 
        "location": "Seattle, USA",
        "date":  "September 2011",},
    "hquery":{
        "title": "Answering Queries using Humans, Algorithms and Databases",  
        "link": "http://ilpubs.stanford.edu:8090/986",  
        "talklink": "talks/answering-queries.pptx",
        "authors": "Aditya Parameswaran and Neoklis Polyzotis",
        "type": "Conference on Innovative Database Research (CIDR)", 
        "location": "Asilomar, USA",
        "date":  "January 2011"},
    "prereq-general":{
        "title": "Evaluating, Combining and Generalizing Recommendations with Prerequisites",  
        "link": "http://ilpubs.stanford.edu:8090/939",  
        "talklink": "talks/evaluating-prerequisites.pptx",
        "authors": "Aditya Parameswaran, Hector Garcia-Molina and Jeffrey D. Ullman,", 
        "type": "19th International Conf. on Information and Knowledge Management (CIKM)", 
        "location": "Toronto, Canada",
        "date":  "October 2010"},
    "concepts":{
        "title": "Towards the Web of Concepts: Extracting Concepts from Large Datasets",  
        "link": "http://ilpubs.stanford.edu:8090/917/",  
        "link": "talks/extracting-concepts.pptx pptx",
        "authors": "Aditya Parameswaran, Hector Garcia-Molina and Anand Rajaraman", 
        "type": "36th International Conf. on Very Large Data Bases (VLDB)", 
        "location": "Singapore",
        "date":  "September 2010", 
        "special": "(Invited to: Special Issue of VLDB Journal for VLDB 2010 Best Papers.)",
        },
    "recsplorer":{
        "title": "Recsplorer: Recommendation Algorithms Based on Precedence Mining",  
        "link": "http://ilpubs.stanford.edu:8090/960/",  
        "talklink": "talks/recsplorer.pptx",
        "authors": "Aditya Parameswaran, Georgia Koutrika, Benjamin Berkovitz and Hector Garcia-Molina,", 
        "type": "SIGMOD International Conf. on Management of Data", 
        "location": "Indianapolis, USA",
        "date":  "June 2010"},
    "views":{
        "title": "Synthesizing View Definitions from Data",  
        "link": "http://ilpubs.stanford.edu:8090/941",  
        "talklink": "talks/synthesizing-views.pptx",
        "authors": "Anish Das Sarma, Aditya Parameswaran, Hector Garcia-Molina and Jennifer Widom",
        "type": "13th International Conf. on Database Theory (ICDT)", 
        "location": "Lausanne, Switzerland",
        "date":  "March 2010",
        },
    "courserank":{
        "title": "Social Sites Research Through CourseRank",  
        "link": "http://data-people.cs.illinois.edu/papers/social-sites-research.pdf",  
        "authors": "Benjamin Berkovitz, Filip Kaliszan, Georgia Koutrika, Henry Liou, Aditya Parameswaran, Petros Venetis, Zahra Mohammadi Zadeh and Hector Garcia-Molina,", 
        "type": "SIGMOD Record",
        "location": "Volume XXX",
        "date": "December 2009",
        },
    "prereq":{
        "title": "Recommendations with Prerequisites (Short Paper)",  
        "link": "http://ilpubs.stanford.edu:8090/938", 
        "authors": "Aditya Parameswaran and Hector Garcia-Molina",
        "type": "3rd ACM Conference on Recommender Systems", 
        "location": "New York, USA",
        "date":  "October 2009"},
    "blogs": {
        "title": "Blogs as Predictors of Movie Success (Short Paper)",  
        "link": "http://ilpubs.stanford.edu:8090/906",  
        "authors": "Eldar Sadikov, Aditya Parameswaran and Petros Venetis,", 
        "type": "AAAI Conf. on Weblogs and Social Media (ICWSM) 2009",
        "location": "San Jose, USA",
        "date":  "May 2009"},
    "flow-complex":{
        "title": "Robust Construction of the Three-dimensional Flow Complex",  
        "link": "http://portal.acm.org/citation.cfm?id=1377676.1377705", 
        "authors": "Frederic Cazals, Aditya Parameswaran and Sylvain Pion,", 
        "type": "ACM Symposium on Computational Geometry (SOCG) 2008", 
        "location": "Maryland, USA",
        "date":  "June 2008"},

}